version: '3.1'
services:
  postgres:
    image: postgres:10-alpine
    container_name: jar-jar-postgres
    environment:
      POSTGRES_PASSWORD: jarjarspringservice
      POSTGRES_USER: jarjarspringservice
      POSTGRES_DB: jarjarspringservice
    stdin_open: true
    tty: true
    ports:
      - 5432:5432/tcp
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
  pg-flyway:
    container_name: jar-jar-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://postgres/jarjarspringservice -schemas=jarjarspringservice -user=jarjarspringservice -password=jarjarspringservice migrate
    volumes:
      - ./docker/pg-flyway/migrations:/flyway/sql
    depends_on:
      - postgres
  app:
    build: .
    restart: always
    container_name: jar-jar-app
    ports:
      - 8080:8080
    depends_on:
      - postgres
