version: '3.1'
services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres10
    environment:
      POSTGRES_PASSWORD: plickservice
      POSTGRES_USER: plickservice
      POSTGRES_DB: plickservice
    stdin_open: true
    tty: true
    ports:
      - 5432:5432/tcp
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
  pg-flyway:
    container_name: pg-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://postgres/plickservice -schemas=plickservice -user=plickservice -password=plickservice migrate
    volumes:
      - ./docker/pg-flyway/migrations:/flyway/sql
    depends_on:
      - postgres
